// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jacobbrewer1/wolf/cmd/bot/config"
	"github.com/Jacobbrewer1/wolf/pkg/logging"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	name := _wireNameValue
	config := logging.NewConfig(name)
	logger, err := logging.CommonLogger(config)
	if err != nil {
		return nil, err
	}
	router := mux.NewRouter()
	app := NewApp(logger, router)
	return app, nil
}

var (
	_wireNameValue = logging.Name(config.AppName)
)
