# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Code Approval"

on:
  merge_group:
  workflow_dispatch: 
  pull_request:
    branches: [
      "main",
      "develop"
    ]
    types:
      - opened
      - reopened
      - synchronize # source branch updated

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  golang-ci-lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      # Sets up golang
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Configure git for private modules"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://x:${GITHUB_API_TOKEN}@github.com".insteadOf "https://github.com"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          only-new-issues: true
          args: --verbose --timeout 5m

  code-approval:
    name: "Code Approval"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: "Configure git for private modules"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://x:${GITHUB_API_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Fetch dependencies
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
